analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3467477,"name"\:"Sample - HR Web App \#3467477","teamId"\:3451771,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3490191,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3451771,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
