<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_uniform-id_gender1</name>
   <tag></tag>
   <elementGuidId>88022348-cb0a-49c1-ae07-82f42785c4e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.radio-inline:nth-child(3) [data-qa=&quot;title&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' radio-inline ') and (position() = 3)]//*[@data-qa = 'title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#uniform-id_gender1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b5930f4e-5097-4a03-a896-f46c72ef54ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2dd1b013-7c46-4873-9e27-f08de36c4949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-qa</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>b3608721-c07e-453f-a8db-95b97a096646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniform-id_gender1</value>
      <webElementGuid>c4ff1139-5bc4-4e93-894c-5eb85914f748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-faa5267a7c8954acfeb3a2db1f7febfa</value>
      <webElementGuid>1a9d2704-214e-4cd3-89a3-cfadda6371b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' radio-inline ') and (position() = 3)]//*[@data-qa = 'title']</value>
      <webElementGuid>e2188625-bab9-49aa-967a-fd2fcfa74a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' radio-inline ') and (position() = 3)]//*[@data-qa = 'title']</value>
      <webElementGuid>0c25a059-bf0f-42a4-a99a-41d7b68c6518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uniform-id_gender1']</value>
      <webElementGuid>85d9744c-92cf-47fe-a462-1d256327c2a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
