name: Katalon Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1920x1080x24 &

      - name: Katalon Studio GitHub Action
        uses: katalon-studio/katalon-studio-github-action@v4.0
        env:
          DISPLAY: :99
        with:
          version: "11.1.3"
          projectPath: "${{ github.workspace }}"
          args: '-noSplash -retry=0 -testSuitePath="Test Suites/TS_Authentication" -browserType="Chrome (headless)" -apiKey=${{ secrets.KATALON_API_KEY }} --config -webui.autoUpdateDrivers=true'
